### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by gmmoura** [dzwaneveld/tudelft-report-thesis-template#4]
Thanks for the template.

I did a couple of changes here, which you may want to consider (all changes on `report.tex`, but can be also done on the template file):

1. Improve space between paragraphs:  `\setlength{\parskip}{0.5em}`
2.  Use a font other than `Arial`:
 ```
 \usepackage[T1]{fontenc}
 \usepackage{palatino}
 \usepackage[fontsize=10.8pt]{fontsize}
```

**Comment by dzwaneveld** [comment]
Thank you for your suggestions! Here are my considerations:

1. If the pages are filled with text, a bit more spacing is definitely a welcoming change. I'm somewhat hesitant to implement this change for the following reasons: (1) Given that this might be somewhat subjective, I am tempted to stick with the default behavior to avoid any confusion; (2) A significant portion of the questions I received were about putting more content on less pages, so they would all have to revert this change (to be fair, amount of pages is a terrible metric). As it is easy to implement, I will see if I can add a hint somewhere (possibly in the FAQ or as a commented additional command).

2. Great suggestion, because the text looks better and becomes more readable. I have considered moving away from Arial in the past, but that would basically entail abandoning the TU Delft house style. This template is more or less a rewrite of the report template provided by the TU Delft. It used to look practically identical (except for the cover page), but TU Delft stopped providing a download. Given that there is not really a template style to follow anymore, I am again tempted to follow through with the changes I have considered in the past (such as the font). It might take some time though.

If you have any other suggestions, I would be happy to know!

**Comment by dzwaneveld** [comment]
After careful consideration, I have decided to stick with Arial for now. Although I might still reconsider in the future, I have implemented Palatino as fallback in case pdfLaTeX is used (as of v1.5). If pdfLaTeX is detected, the following will activate:

```LaTeX
%% pdfLaTeX is available for compatibility and uses a Paletino-like font
\RequirePackage[T1]{fontenc}  % Selecting T1 font encoding
\RequirePackage{newpxtext}    % Palatino-like font...
\RequirePackage{newpxmath}    % ...with support for mathematics
```

The other two suggestions (changing fontsize and the parskip length) ultimately feel like personal changes. I have actually removed a few of my own personal changes over time, so that anyone using the template would be able to make those choices by themselves. I might add something in the FAQ later, but it is not a priority for me right now.

Let me know if you have any other suggestions, I would be happy to know!
