### ISSUE TITLE
Change title font to new TU Delft title font

### ISSUE THREAD

**Issue by rickstaa** [dzwaneveld/tudelft-report-thesis-template#6]
It looks like, as of 18/07/2022, TU Delft has updated the title typography identity to RobotoSlab (see https://www.tudelft.nl/huisstijl/bouwstenen/typografie). Maybe we should update the template to reflect this change (see #5).

**Comment by dzwaneveld** [comment]
Looping back around: Roboto Slab will now (as part of #7) also be used as title font when pdfLaTeX is set as the compiler. Oddly enough, the boldface of any fontseries will always result in Roboto Slab Bold (instead of going from Thin > Light > Regular > Bold). As support for pdfLaTeX mostly exists for compatibility, that behavior seems fine. 

A solution that takes all Roboto Slab Bold and makes it regular Roboto Slab is the following. For anyone reading along that would like to use pdfLaTeX with Roboto Slab regular as boldface: simply add the two commands to the preamble.

```latex
\input{T1RobotoSlab-TLF.fd}
\DeclareFontShape{T1}{RobotoSlab-TLF}{b}{n} { <-> ssub * RobotoSlab-TLF/m/n }{}
```
